In [22]:
import numpy as np
from PIL import Image
import os, cv2


In [23]:
'''
人脸识别训练器
'''
name ="zd"
path = os.path.join(os.getcwd()+"/data/"+name+"/")
faces = []
ids = []
pictures = {}


In [24]:

# 以 numpy 格式存储图像，并将用户的 id 存储在 imageNp 和 id 列表中的同一索引上
for root,dirs,files in os.walk(path):
    pictures = files

In [25]:
for pic in pictures :
    imgpath = path+pic
    #L模式图像，则意味着它是单通道图像 - 通常解释为灰度
    # L就是存储亮度的方法。它非常紧凑，但只存储灰度，不存储颜色。
    img = Image.open(imgpath).convert('L')
   
    # 图像转换为np
    imageNp = np.array(img, 'uint8')
    print("imageNp",imageNp)
    # 得到名字
    id = int(pic.split(name)[0])
    print("id",id)
    faces.append(imageNp)
    ids.append(id)

imageNp [[  2   0   2 ...   0   4   0]
 [  0   3   0 ...   1   0   0]
 [  2   0 131 ... 144 157   2]
 ...
 [  0   1  42 ... 220 215   1]
 [  0   5  37 ... 221 217   1]
 [  0   0   2 ...   2   1   1]]
id 92
imageNp [[  2   1   1 ...   2   0   1]
 [  1   3   1 ...   1   2   0]
 [  3   0 111 ... 115 112   1]
 ...
 [  0   1  11 ...  46  41   0]
 [  1   2  10 ...  41  33   3]
 [  0   0   2 ...   0   3   0]]
id 185
imageNp [[  2   1   0 ...   2   2   0]
 [  1   2   1 ...   2   1   3]
 [  0   0  94 ... 100 101   0]
 ...
 [  0   1   4 ...  29  30   0]
 [  0   2   5 ...  27  25   1]
 [  0   0   0 ...   0   3   0]]
id 178
imageNp [[  1   2   1 ...   1   0   0]
 [  4   1   1 ...   0   0   5]
 [  1   2  46 ... 143 141   0]
 ...
 [  1   0  70 ...  40  68   0]
 [  0   5  62 ...  42  68   3]
 [  2   0   3 ...   1   3   0]]
id 9
imageNp [[  1   1   0 ...   1   1   0]
 [  1   0   2 ...   0   0   0]
 [  1   3 103 ... 111 113   1]
 ...
 [  0   0  40 ...  44  39   0]
 [  0   6  33 ...  46  39   2]
 [  0  

In [27]:

ids = np.array(ids)
print(ids)
#x训练保存分类器
clf = cv2.face.LBPHFaceRecognizer_create()
# (src,label)
clf.train(faces, ids)
# clf.write("./data/classifiers/"+name+"_classifier.xml")


[ 92 185 178   9 100 145  17  52 201  33  76 124 161 119  49 126 163  31
  74  89  15  50 102 147  28 187  90  11  54 106 143 183  94  69 122 167
  35  70  37  72 120 165 198 158 139  96 181 104 141  13  56 162 127  75
  30  88  48  29 186  91  51  14 146 103 144 101  53  16 200   8  93 184
 179 118  77  32 160 125 159  73  36 164 121 199 140 105  57  12 138  97
 180 182  95  68  55  10 142 107 166 123  71  34  40 112 157 197  80  38
   2  59  99 136 173  21  64  23  66 134 171   0 109 168  82 195 110 155
  42  86 191 129 114 151  46 188  27  62 130 175 148   4  18   6 132 177
  25  60  44 116 153  79 193  84 108   1  67  22 170 135 154 111  43 169
  83 194 196  81  39  41 156 113  98 172 137  65  20  58   3 176 133  61
  24   7  19  78 192  85  45 152 117 150 115  47  87 190 128   5 149 189
  63  26 174 131]
